### ISSUE TITLE
PCBs

### ISSUE THREAD

**Issue by danko79** [Retro-Commodore/RCEU1264-C64-PSU#3]
Hi, sorry if allow myself to open an issue but i don't know how to contact you, i wanted to know if you have some of your pcb's for sale?

**Comment by tomse** [comment]
I don't have any pcb's for sale, but you can order 5 by yourself using i.e. jlcpcb.com 
create an account, click on quote, and upload the zip file from the Gerbers directory.  5pcs for $2 + shipping, I can't make it cheaper selling just 1 for you.
